<?xml version='1.0'?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro" name='gibbon'>
    <xacro:include filename="$(find gibbon)/urdf/materials.xacro" />
    <xacro:property name="PI" value="3.1415926535897931"/>
    <xacro:property name="arm_radius" value="0.01" />
    <xacro:property name="arm_len" value="0.8" />
    <xacro:property name="arm_mass" value="1.0" />
    <xacro:property name="width" value="0.2" />
    <xacro:property name="polelen" value="0.0001" />

    <xacro:macro name="box_inertia" params="mass width height">
      <inertia 
        ixx="${mass / 12.0 * (width*width + height*height)}" 
        ixy="0.0" 
        ixz="0.0" 
        iyy="${mass / 12.0 * (height*height + width*width)}" 
        iyz="0.0" 
        izz="${mass / 12.0 * (width*width + width*width)}"/>
    </xacro:macro>

    <!-- <link name="world"/>

    <joint name="fixed" type="fixed">
      <parent link="world"/>
      <child link="link_1"/>
    </joint> -->

    <link name='link_1'>
      <collision>
        <origin rpy="0 0 0" xyz="0 0 -${arm_len/2}"/>
        <geometry>
          <!-- <cylinder radius="${arm_radius}" length="${arm_len}"/> -->
          <box size="${arm_radius} ${arm_radius} ${arm_len}"/>
        </geometry>
      </collision>
      <visual>
        <origin rpy="0 0 0" xyz="0 0 -${arm_len/2}"/>
        <material name="grey2"/>
        <geometry>
          <!-- <cylinder radius="${arm_radius}" length="${arm_len}"/> -->
          <box size="${arm_radius} ${arm_radius} ${arm_len}"/>
        </geometry>
      </visual>
      <inertial>
        <mass value="${arm_mass}" />
        <origin rpy="0 0 0" xyz="0 0 -${arm_len/2}"/>
        <xacro:box_inertia mass="${arm_mass}" width="${arm_radius}" height="${arm_len}" />
      </inertial>
    </link>

    <link name="link_1_tip">
      <inertial>
        <mass value="0.001" />
        <origin rpy="0 0 0" xyz="0 0 0"/>
        <xacro:box_inertia mass="0.001" width="0.001" height="0.001" />
      </inertial>
    </link>
    <!-- <link name="link_1_tip" /> -->
    <joint name="link_1__link_1_tip" type="revolute">
      <parent link="link_1_tip"/>
      <child link="link_1"/>
      <origin rpy="0 0 0" xyz="0 0 -0.1"/>
      <limit lower="0" upper="0" effort="0" velocity="0"/>
    </joint>

    <link name='link_2'>
      <collision>
        <origin rpy="0 0 0" xyz="0 0 ${arm_len/2}"/>
        <geometry>
          <!-- <cylinder radius="${arm_radius}" length="${arm_len}"/> -->
          <box size="${arm_radius} ${arm_radius} ${arm_len}"/>
        </geometry>
      </collision>
      <visual>
        <origin rpy="0 0 0" xyz="0 0 ${arm_len/2}"/>
        <material name="grey1"/>
        <geometry>
          <!-- <cylinder radius="${arm_radius}" length="${arm_len}"/> -->
          <box size="${arm_radius} ${arm_radius} ${arm_len}"/>
        </geometry>
      </visual>
      <inertial>
        <origin rpy="0 0 0" xyz="0 0 ${arm_len/2}"/>
        <mass value="${arm_mass}" />
        <xacro:box_inertia mass="${arm_mass}" width="${arm_radius}" height="${arm_len}" />
      </inertial>
    </link>

    <link name="link_2_tip">
      <inertial>
        <mass value="${arm_mass}" />
        <origin rpy="0 0 0" xyz="0 0 -${arm_len/2}"/>
        <xacro:box_inertia mass="${arm_mass}" width="${arm_radius}" height="${arm_len}" />
      </inertial>
    </link>
    <joint name="link_2__link_2_tip" type="revolute">
      <parent link="link_2"/>
      <child link="link_2_tip"/>
      <origin rpy="0 0 0" xyz="${2*arm_radius} 0 ${arm_len + 0.1}"/>
      <limit lower="0" upper="0" effort="0" velocity="0"/>
    </joint>

    <joint name="link_1__link_2" type="continuous">
      <parent link="link_1"/>
      <child link="link_2"/>
      <!-- <limit effort="1000.0" lower="${-2*PI}" upper="${2*PI}" velocity="30.0"/> -->
      <origin rpy="${PI} 0 0" xyz="${2 * arm_radius + 0.001} 0 -${arm_len}"/>
      <dynamics friction="0.0" damping="0.0"/>
    </joint>
    <transmission name="link_1__link_2_trans">
      <type>transmission_interface/SimpleTransmission</type>
      <actuator name="link_1__link_2_motor">
        <hardwareInterface>hardware_interface/EffortJointInterface</hardwareInterface>
        <mechanicalReduction>1</mechanicalReduction>
      </actuator>
      <joint name="link_1__link_2">
        <hardwareInterface>hardware_interface/EffortJointInterface</hardwareInterface>
      </joint>
    </transmission>

    <joint name="link_1__gripper" type="fixed">
      <parent link="link_1"/>
      <child link="link_1_gripper_pole"/>
      <origin rpy="0 -${PI/2} 0" xyz="0 0 0"/>
    </joint>

    <joint name="link_2__gripper" type="fixed">
      <parent link="link_2"/>
      <child link="link_2_gripper_pole"/>
      <origin rpy="0 -${PI/2} 0" xyz="0 0 ${arm_len}"/>
    </joint>

    <link name="link_1_gripper_pole">
      <visual>
        <geometry>
          <cylinder length="${polelen}" radius="${polelen}"/>
        </geometry>
        <origin xyz="0 0 0" rpy="0 0 0 "/>
      </visual>
      <collision>
        <geometry>
          <cylinder length="${polelen}" radius="0.01"/>
        </geometry>
        <origin xyz="0 0 0" rpy="0 0 0 "/>
      </collision>
      <inertial>
        <mass value="${polelen}" />
        <origin xyz="0 0 0" rpy="0 0 0 "/>
        <xacro:box_inertia mass="${polelen}" width="${polelen}" height="${polelen}" />
      </inertial>
    </link>

    <link name="link_2_gripper_pole">
      <visual>
        <geometry>
          <cylinder length="${polelen}" radius="${polelen}"/>
        </geometry>
        <origin xyz="0 0 0" rpy="0 0 0 "/>
      </visual>
      <collision>
        <geometry>
          <cylinder length="${polelen}" radius="0.01"/>
        </geometry>
        <origin xyz="0 0 0" rpy="0 0 0 "/>
      </collision>
      <inertial>
        <mass value="${polelen}" />
        <origin xyz="0 0 0" rpy="0 0 0 "/>
        <xacro:box_inertia mass="${polelen}" width="${polelen}" height="${polelen}" />
      </inertial>
    </link>

    <xacro:macro name="gripper" params="prefix reflect link_name">
      <joint name="${link_name}_${prefix}_gripper_joint" type="revolute">
        <axis xyz="0 0 ${reflect}"/>
        <limit effort="1000.0" lower="0.0" upper="3" velocity="30"/>
        <origin rpy="0 0 0" xyz="${polelen} ${reflect*0.01} 0"/>
        <parent link="${link_name}_gripper_pole"/>
        <child link="${link_name}_${prefix}_gripper"/>
      </joint>
      <transmission name="${link_name}_${prefix}_gripper_joint_trans">
        <type>transmission_interface/SimpleTransmission</type>
        <actuator name="${link_name}_${prefix}_gripper_joint_motor">
          <hardwareInterface>hardware_interface/PositionJointInterface</hardwareInterface>
          <mechanicalReduction>1</mechanicalReduction>
        </actuator>
        <joint name="${link_name}_${prefix}_gripper_joint">
          <hardwareInterface>hardware_interface/PositionJointInterface</hardwareInterface>
        </joint>
      </transmission>
      <link name="${link_name}_${prefix}_gripper">
        <visual>
          <origin rpy="${reflect*PI/2} 0 ${reflect*PI/2}" xyz="0.05 0 0"/>
          <geometry>
            <box size="0.001 0.02 0.1"/>
          </geometry>
        </visual>
        <collision>
          <origin rpy="${reflect*PI/2} 0 ${reflect*PI/2}" xyz="0.05 0 0"/>
          <geometry>
            <box size="0.001 0.02 0.1"/>
          </geometry>
        </collision>
        <visual>
          <origin rpy="0 0.0 ${reflect * 0.7}" xyz="0.104 ${-1*reflect*0.005} 0"/>
          <geometry>
            <box size="0.001 0.01 0.02"/>
          </geometry>
        </visual>
        <collision>
          <origin rpy="0 0.0 ${reflect * 0.7}" xyz="0.104 ${-1*reflect*0.005} 0"/>
          <geometry>
            <box size="0.001 0.01 0.02"/>
          </geometry>
        </collision>
        <inertial>
          <mass value="0.1" />
          <origin rpy="0 0 0" xyz="0 0 0"/>
          <xacro:box_inertia mass="0.1" width="0.1" height="0.1" />
        </inertial>
      </link>
    </xacro:macro>

    <xacro:gripper prefix="left" reflect="1" link_name="link_1" />
    <xacro:gripper prefix="right" reflect="-1" link_name="link_1" />
    <xacro:gripper prefix="left" reflect="1" link_name="link_2" />
    <xacro:gripper prefix="right" reflect="-1" link_name="link_2" />

    <gazebo reference="link_1">
      <material>Gazebo/Red</material>
      <mu1>1e-01</mu1>
      <mu2>1e-01</mu2>
    </gazebo>
    <gazebo reference="link_2">
      <mu1>1e-01</mu1>
      <mu2>1e-01</mu2>
    </gazebo>
    <!-- <gazebo reference="link_1_left_gripper">
      <mu1>1e-01</mu1>
      <mu2>1e-01</mu2>
      <kp>0</kp>
      <kd>0</kd>
    </gazebo>
    <gazebo reference="link_1_right_gripper">
      <mu1>1e-01</mu1>
      <mu2>1e-01</mu2>
      <kp>0</kp>
      <kd>0</kd>
    </gazebo>
    <gazebo reference="link_2_left_gripper">
      <mu1>1e-01</mu1>
      <mu2>1e-01</mu2>
      <kp>0</kp>
      <kd>0</kd>
    </gazebo>
    <gazebo reference="link_2_right_gripper">
      <mu1>1e-01</mu1>
      <mu2>1e-01</mu2>
      <kp>0</kp>
      <kd>0</kd>
    </gazebo> -->

    <gazebo>
      <plugin name="gazebo_ros_control" filename="libgazebo_ros_control.so">
        <robotNamespace>/gibbon</robotNamespace>
        <robotSimType>gazebo_ros_control/DefaultRobotHWSim</robotSimType>
      </plugin>
    </gazebo>
</robot>