<?xml version='1.0'?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro" name='monkey'>

    <xacro:property name="arm_radius" value="0.02" />
    <xacro:property name="arm_len" value="0.7" />
    <xacro:property name="PI" value="3.14159265359" />
    <material name="grey1"><color rgba="1 1 1 1"/></material>
    <material name="grey2"><color rgba="0.31 0.31 0.31 1"/></material>

    <link name='link_1'>
      <origin rpy="0 0 0" xyz="0 0 0"/>
      <visual name='visual'>
        <origin rpy="0 0 0" xyz="0 0 -${arm_len/2}"/>
        <material name="grey2"/>
        <geometry>
          <cylinder radius="${arm_radius}" length="${arm_len}"/>
        </geometry>
      </visual>
    </link>

    <link name='link_2'>
      <origin rpy="0 0 0" xyz="${arm_radius*2} 0 0"/>
      <visual name='visual'>
        <origin rpy="0 0 0" xyz="${arm_radius*2} 0 -${arm_len/2}"/>
        <material name="grey1"/>
        <geometry>
          <cylinder radius="${arm_radius}" length="${arm_len}"/>
        </geometry>
      </visual>
    </link>
</robot>