<?xml version='1.0'?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro" name='gibbon'>

    <xacro:property name="arm_radius" value="0.01" />
    <xacro:property name="arm_len" value="1" />
    <xacro:property name="arm_mass" value="1.0" />
    <xacro:property name="width" value="0.2" />
    <xacro:property name="polelen" value="0.0" />

    <material name="grey1"><color rgba="0.7 0.7 0.7 1"/></material>
    <material name="grey2"><color rgba="0.9 0.9 0.9 1"/></material>

    <xacro:macro name="default_inertial" params="mass">
      <inertial>
        <mass value="${mass}" />
        <inertia ixx="1.0" ixy="0.0" ixz="0.0" iyy="1.0" iyz="0.0" izz="1.0" />
      </inertial>
    </xacro:macro>

    <xacro:macro name="arm_inertial" params="mass len">
      <inertial>
        <mass value="${mass}" />
        <inertia ixx="${1.0 / 3.0 * mass * len * len}" ixy="0.0" ixz="0.0" iyy="${1.0 / 3.0 * mass * len * len}" iyz="0.0" izz="0.0" />
      </inertial>
    </xacro:macro>

    <link name="base_link"/>
    <joint name="base_link__link_1" type="fixed">
      <parent link="base_link"/>
      <child link="link_1"/>
      <origin rpy="0 0 0" xyz="0 0 0"/>
    </joint>

    <link name='link_1'>
      <visual>
        <origin rpy="0 0 0" xyz="0 0 -${arm_len/2}"/>
        <material name="grey2"/>
        <geometry>
          <cylinder radius="${arm_radius}" length="${arm_len}"/>
        </geometry>
      </visual>
      <collision>
        <origin rpy="0 0 0" xyz="0 0 -${arm_len/2}"/>
        <geometry>
          <cylinder radius="${arm_radius}" length="${arm_len}"/>
        </geometry>
      </collision>
      <xacro:arm_inertial mass="${arm_mass}" len="${arm_len}"/>
    </link>

    <link name='link_2'>
      <visual>
        <origin rpy="0 0 0" xyz="${arm_radius*2} 0 -${arm_len/2}"/>
        <material name="grey1"/>
        <geometry>
          <cylinder radius="${arm_radius}" length="${arm_len}"/>
        </geometry>
      </visual>
      <collision>
        <origin rpy="0 0 0" xyz="${arm_radius*2} 0 -${arm_len/2}"/>
        <geometry>
          <cylinder radius="${arm_radius}" length="${arm_len}"/>
        </geometry>
      </collision>
      <xacro:arm_inertial mass="${arm_mass}" len="${arm_len}"/>
    </link>

    <joint name="link_1__link_2" type="revolute">
      <parent link="link_1"/>
      <child link="link_2"/>
      <limit effort="100000.0" lower="${-pi}" upper="${pi}" velocity="3.14"/>
      <origin rpy="0 0 0" xyz="${arm_radius} 0 -${arm_len}"/>
    </joint>
    <transmission name="link_1__link_2_trans">
      <type>transmission_interface/SimpleTransmission</type>
      <actuator name="$link_1__link_2_motor">
        <hardwareInterface>hardware_interface/PositionJointInterface</hardwareInterface>
        <mechanicalReduction>1</mechanicalReduction>
      </actuator>
      <joint name="link_1__link_2">
        <hardwareInterface>hardware_interface/PositionJointInterface</hardwareInterface>
      </joint>
    </transmission>

    <joint name="link_1__gripper" type="fixed">
      <parent link="link_1"/>
      <child link="link_1_gripper_pole"/>
      <origin rpy="0 -${pi/2} 0" xyz="0 0 0"/>
    </joint>

    <joint name="link_2__gripper" type="fixed">
      <parent link="link_2"/>
      <child link="link_2_gripper_pole"/>
      <origin rpy="0 ${pi/2} 0" xyz="${arm_radius*2} 0 -${arm_len}"/>
    </joint>

    <link name="link_1_gripper_pole">
      <visual>
        <geometry>
          <cylinder length="${polelen}" radius="0.01"/>
        </geometry>
        <origin xyz="0 0 0" rpy="0 0 0 "/>
      </visual>
      <collision>
        <geometry>
          <cylinder length="${polelen}" radius="0.01"/>
        </geometry>
        <origin xyz="0 0 0" rpy="0 0 0 "/>
      </collision>
      <xacro:default_inertial mass="0.001"/>
    </link>

    <link name="link_2_gripper_pole">
      <visual>
        <geometry>
          <cylinder length="${polelen}" radius="0.01"/>
        </geometry>
        <origin xyz="0 0 0" rpy="0 0 0 "/>
      </visual>
      <collision>
        <geometry>
          <cylinder length="${polelen}" radius="0.01"/>
        </geometry>
        <origin xyz="0 0 0" rpy="0 0 0 "/>
      </collision>
      <xacro:default_inertial mass="0.001"/>
    </link>

    <xacro:macro name="gripper" params="prefix reflect link_name">
      <joint name="${link_name}_${prefix}_gripper_joint" type="revolute">
        <axis xyz="0 0 ${reflect}"/>
        <limit effort="100000.0" lower="0.0" upper="0.548" velocity="3.14"/>
        <origin rpy="0 0 0" xyz="${polelen} ${reflect*0.01} 0"/>
        <parent link="${link_name}_gripper_pole"/>
        <child link="${link_name}_${prefix}_gripper"/>
      </joint>
      <transmission name="${link_name}_${prefix}_gripper_joint_trans">
        <type>transmission_interface/SimpleTransmission</type>
        <actuator name="$${link_name}_${prefix}_gripper_joint_motor">
          <hardwareInterface>hardware_interface/PositionJointInterface</hardwareInterface>
          <mechanicalReduction>1</mechanicalReduction>
        </actuator>
        <joint name="${link_name}_${prefix}_gripper_joint">
          <hardwareInterface>hardware_interface/PositionJointInterface</hardwareInterface>
        </joint>
      </transmission>
      <link name="${link_name}_${prefix}_gripper">
        <visual>
          <origin rpy="${reflect*pi/2} 0 ${reflect*pi/2}" xyz="0.05 0 0"/>
          <geometry>
            <box size="0.001 0.02 0.1"/>
          </geometry>
        </visual>
        <collision>
          <geometry>
            <box size="0.001 0.02 0.1"/>
          </geometry>
          <origin rpy="${reflect*pi/2} 0 ${reflect*pi/2}" xyz="0.05 0 0"/>
        </collision>
        <visual>
          <origin rpy="0 0 0" xyz="0.1 ${-1*reflect*0.005} 0"/>
          <geometry>
            <box size="0.001 0.01 0.02"/>
          </geometry>
        </visual>
        <collision>
          <geometry>
            <box size="0.001 0.01 0.02"/>
          </geometry>
          <origin rpy="0 0 0" xyz="0.1 ${-1*reflect*0.005} 0"/>
        </collision>
        <xacro:default_inertial mass="0.05"/>
      </link>
    </xacro:macro>

    <xacro:gripper prefix="left" reflect="1" link_name="link_1" />
    <xacro:gripper prefix="right" reflect="-1" link_name="link_1" />
    <xacro:gripper prefix="left" reflect="1" link_name="link_2" />
    <xacro:gripper prefix="right" reflect="-1" link_name="link_2" />

    <gazebo>
      <plugin name="gazebo_ros_control" filename="libgazebo_ros_control.so">
        <robotNamespace>/gibbon</robotNamespace>
      </plugin>
    </gazebo>
</robot>